
" Basic editor environment
set hidden
set wildmenu
set showcmd
set hlsearch

set ignorecase
set smartcase

set autoindent

set ruler

set laststatus=2

set confirm
set visualbell

" Highlighting and tabs
filetype plugin on
filetype indent plugin on
syntax on
set background=dark

set shiftwidth=4
set softtabstop=4
set expandtab
set relativenumber

hi Normal guibg=#161616 ctermbg=none

map <F11> :let &background = ( &background == "dark"? "light" : "dark" )<CR>

filetype plugin indent on
au BufNewFile,BufReadPost *.dasm,*.dasm16 setl shiftwidth=2 expandtab

