
" Generic stuff

set hidden
set wildmenu
set showcmd
set hlsearch

set ignorecase
set smartcase

set autoindent

set ruler

set laststatus=2

set confirm
set visualbell

filetype plugin on
filetype indent plugin on
syntax on

" Coloring on the gui

if has('gui_running')
    colorscheme moria
    hi Normal guibg=#161616 guifg=#AAAAAA ctermbg=none
endif

" Soft tabs of width 4

set shiftwidth=4
set softtabstop=4
set expandtab

" More intuitive backspace

set backspace=indent,eol,start

" Handling line numbers

if exists('&relativenumber')
    set relativenumber

    :au FocusLost * :set number
    :au FocusGained * :set relativenumber

    autocmd InsertEnter * :set number
    autocmd InsertLeave * :set relativenumber

    function! NumberToggle()
        if(&relativenumber == 1)
            set number
        else
            set relativenumber
        endif
    endfunc

    " CTL+N for switching line number mode
    nnoremap <C-n> :call NumberToggle()<cr>

else
    set number
endif

" .dasm support
au BufNewFile,BufReadPost *.dasm,*.dasm16 setl shiftwidth=2 expandtab

function s:MkNonExDir(file, buf)
    if empty(getbufvar(a:buf, '&buftype')) && a:file!~#'\v^\w+\:\/'
        let dir=fnamemodify(a:file, ':h')
        if !isdirectory(dir)
            call mkdir(dir, 'p')
        endif
    endif
endfunction
augroup BWCCreateDir
    autocmd!
    autocmd BufWritePre * :call s:MkNonExDir(expand('<afile>'), +expand('<abuf>'))
augroup END
